---
name: Test-Unix-User
version: 0.02
author:
  - Nik Clayton <nik@FreeBSD.org>
abstract: Test::Builder based tests for Unix users and home directories
license: bsd
requires:
  Test::Builder: 0
  Test::More: 0
  Test::Tester: 0.102
provides:
  Test::Unix::User:
    file: lib/Test/Unix/User.pm
    version: 0.02
generated_by: Module::Build version 0.2611
